package guru.mikelue.foxglove;

import java.sql.JDBCType;
import java.util.EnumSet;
import java.sql.DatabaseMetaData;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import static java.util.stream.Collectors.joining;

/**
 * Metadata of a column.
 *
 * <p>The information could come from:
 *
 * <ul>
 *   <li>{@link DatabaseMetaData#getColumns(String, String, String, String)}</li>
 *   <li>{@link java.sql.ResultSet#getMetaData()}</li>
 * </ul>
 *
 * <hr>
 *
 * <h2>From {@link DatabaseMetaData#getColumns(String, String, String, String)}</h2>
 *
 * The columns mapping to this object are:
 *
 * <ul>
 *   <li><code>COLUMN_NAME</code> - for {@link #name()}</li>
 *   <li><code>TYPE_NAME</code> - for {@link #typeName()}</li>
 *   <li><code>DATA_TYPE</code> - for {@link #jdbcType()}</li>
 *   <li><code>NULLABLE</code> - for {@link Property#NULLABLE}</li>
 *   <li><code>COLUMN_DEF</code> - for {@link Property#DEFAULT_VALUE}</li>
 *   <li><code>IS_AUTOINCREMENT</code> - for {@link Property#AUTO_INCREMENT}</li>
 *   <li><code>IS_GENERATEDCOLUMN</code> - for {@link Property#GENERATED}</li>
 *   <li><code>COLUMN_SIZE</code> - for {@link #size()}</li>
 *   <li><code>DECIMAL_DIGITS</code> - for {@link #decimalDigits()}</li>
 * </ul>
 *
 * @param name The name of the column
 * @param properties The true/false properties of this column
 * @param typeName The name of type for the column
 * @param jdbcType The corresponding {@link JDBCType} of the column
 * @param size The size of the column
 * @param decimalDigits The number of decimal digits of the column(as scale of SQL standard)
 */
public record ColumnMeta(
	String name,
	EnumSet<Property> properties,
	String typeName, JDBCType jdbcType,
	int size, int decimalDigits
) {
	/**
	 * The properties used for auto-generating of a column.
	 *
	 * This type is used with {@link EnumSet} usually.
	 */
	public enum Property {
		/**
		 * Indicates whether the column allows null value.
		 *
		 * This value corresponds to NULLABLE defined by {@link java.sql.DatabaseMetaData#getColumns(String, String, String, String)}.
		 *
		 * For "columnNullable" or "unknown" value of NULLABLE, this value is put into the set.
		 */
		NULLABLE,
		/**
		 * Indicates whether the column has default value.
		 *
		 * This value corresponds to COLUMN_DEF defined by {@link java.sql.DatabaseMetaData#getColumns(String, String, String, String)}.
		 *
		 * For not-null value of COLUMN_DEF, this value is put into the set.
		 */
		DEFAULT_VALUE,
		/**
		 * Indicates whether the column is auto-increment.
		 *
		 * This value corresponds to IS_AUTOINCREMENT defined by {@link java.sql.DatabaseMetaData#getColumns(String, String, String, String)}.
		 *
		 * For "YES" value of IS_AUTOINCREMENT, this value is put into the set.
		 */
		AUTO_INCREMENT,
		/**
		 * Indicates whether the column is generated by database.
		 *
		 * This value corresponds to IS_GENERATEDCOLUMN defined by {@link java.sql.DatabaseMetaData#getColumns(String, String, String, String)}.
		 *
		 * For "YES" value of IS_GENERATEDCOLUMN, this value is put into the set.
		 */
		GENERATED,
	}

	/**
	 * Only use name of column for hash code.
	 *
	 * @return Hash code of column name
	 */
	@Override
	public int hashCode()
	{
		return name.hashCode();
	}

	/**
	 * Only use name and {@link JDBCType} of column for equality check.
	 *
	 * @param obj The other object to be checked
	 *
	 * @return True if the other object is a {@link ColumnMeta} and has same name
	 */
	@Override
	public boolean equals(Object obj)
	{
		if (obj == null) { return false; }
		if (obj == this) { return true; }
		if (obj.getClass() != getClass()) {
			return false;
		}

	   ColumnMeta rhs = (ColumnMeta) obj;
	   return new EqualsBuilder()
			 .append(name(), rhs.name())
			 .isEquals();
	}

	/**
	 * Builds complete properties and descriptive information of column metadata.
	 *
	 * @return The string representation of this column
	 */
	@Override
	public String toString()
	{
		var builder = new ToStringBuilder(this, ToStringStyle.SIMPLE_STYLE)
			.append("name", '"' + name + '"')
			.append(" JDBC<" + jdbcType + ">")
			.append(" (" + typeName + ")");

		if (size > 0) {
			builder.append(" #" + size);
		}

		if (decimalDigits > 0) {
			builder.append(" .[" + decimalDigits + "]");
		}

		if (!properties.isEmpty()) {
			builder.append(
				" " +
				properties.stream()
					.map(p -> "<" + p.name() + ">")
					.collect(joining(", "))
			);
		}

		return builder.toString();
	}
}
