+++
title = 'Default Generators'
description = 'Default generator for various types of columns'
weight = 30
+++

:jdbc_type_link: {jdk-doc}/java.sql/java/sql/JDBCType.html[java.sql.JDBCType]
:value_spec_link: {instancio-core-doc}/org/instancio/generator/ValueSpec.html[ValueSpec]

{foxglove-link} provides default generators based on columns' metadata.

See <<default-spec, Default spec by JDBC Type>> for more details.

== Global setting

* You can get the global setting by `DataSetting.default()`.
* The {foxglove-javadoc-link}/setting/DataSetting.html[DataSetting] provides various methods to change how values are generated for columns.

See link:/docs/settings/[Settings] for more details.

=== Default behavior by DDL

https://en.wikipedia.org/wiki/Data_definition_language[DDL] provides some definitions about the columns,
{foxglove-link}'s default behavior over column definitions are(sorted by priority):

. `Generated`(*FALSE*) - Won't generate values
. `Auto Increament`(*FALSE*) - Won't generate values
. `Nullable`(*TRUE*) - Generate viable(random) values
. `Default value`(*TRUE*) - Generate viable(random) values

---

* Any column has any of above properties will follow the `TRUE/FALSE` to decide
whether or not to generate the value automatically.
* If a column has none of above properties, {foxglove-link} will generate viable(random) values for it.
* You can change the behavior by `DataSetting.autoGenerateFor()` and `DataSetting.notAutoGenerateFor()`.
* For nullable column, you can generate possible `NULL` value by setting `DataSetting.generateNull(true)` or
	{value_spec_link}'s `nullable()` method.

NOTE: These properties are ignored if a {foxglove-javadoc-link}/TableFacet.html[TableFacet] define its own logic for a matched column.

See {foxglove-javadoc-link}/setting/DataSetting.html[DataSetting] of javadoc for more details.

== Default number of rows

NOTE: The default number of rows(to be generated) is `1024`.

Use `DataSetting.setDefaultNumberOfRows(int)` to change the it.

[[default-spec]]
== Default spec by JDBC Type

Depends on {jdbc_type_link}, {foxglove-link} provides default generators for:

=== For integral data

The min value of integral types would be equals to `0`.

[cols="2,2"]
|===
|JDBC Type
|Default Generator

|*BIT*, *BOOLEAN*
|{instancio-core-doc}/org/instancio/generator/specs/BooleanSpec.html[BooleanSpec]

|*TINYINT*
|{instancio-core-doc}/org/instancio/generator/specs/ByteSpec.html[ByteSpec]

|*SMALLINT*
|{instancio-core-doc}/org/instancio/generator/specs/ShortSpec.html[ShortSpec]

|*INTEGER*
|{instancio-core-doc}/org/instancio/generator/specs/IntegerSpec.html[IntegerSpec]

|*BIGINT*
|{instancio-core-doc}/org/instancio/generator/specs/LongSpec.html[LongSpec]
|===

=== For floating point data

[cols="2,2"]
|===
|JDBC Type
|Default Generator

|*FLOAT*, *REAL*
|{instancio-core-doc}/org/instancio/generator/specs/FloatSpec.html[FloatSpec]

Min value would be equals to `0.0f`.
|*DOUBLE*
|{instancio-core-doc}/org/instancio/generator/specs/DoubleSpec.html[DoubleSpec]

Min value would be equals to `0.0f`.
|*NUMERIC*, *DECIMAL*
|{instancio-core-doc}/org/instancio/generator/specs/BigDecimalSpec.html[BigDecimalSpec]
|===

For `BigDecimalSpec`, the precision would be equals to `ColumnMeta.size()`, `ColumnMeta.decimalDigits()`.

---

TODO: PostgreSQL supports negative value of scale for `NUMERIC(4, -3)`, which should be implemented specifically.

.Special note of PostgreSQL
____
PostgreSQL permits the scale in a numeric type declaration to be any value
	in the range -1000 to 1000.
However, the SQL standard requires the scale to be in the range 0 to precision.
Using scales outside that range may not be portable to other database systems.
____

See https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL[PostgreSQL Numeric Types] for more details.

=== For text data

By default, all of characters type are generated by `alphaNumeric()` of {instancio-core-doc}/org/instancio/generator/specs/StringGeneratorSpec.html[StringGeneratorSpec].

For `CHAR`, `VARCHAR`, `NCHAR`, `NVARCHAR`::
+
[cols="2,2"]
|===
|`ColumnMeta.size()`
|ValueGenerator

| `<= 8`(less than or equal to 8)
| Same as `ColumnMeta.size()`

| `> 8 && <= 32`(between 8 and 32)
| Length is between 8 and `ColumnMeta.size()`

| `> 32`(more than 32)
| Length is between 32 and `Math.min(ColumnMeta.size(), 128)`
|===

For `LONGVARCHAR`, `CLOB`, `LONGNVARCHAR`, `NCLOB`::
+
* Generate text with length between `_1024_` and `_2048_`.

Customization of large text:

* Use `DataSetting.largeTextLength(minLength, maxLength)` to change the random length for large text columns.

=== For date/time/timestamp

[cols="2,2"]
|===
|JDBC Type
|Default Generator

|*DATE*
|{instancio-core-doc}/org/instancio/generator/specs/LocalDateSpec.html[LocalDateSpec]

|*TIME*
|{instancio-core-doc}/org/instancio/generator/specs/LocalTimeSpec.html[LocalTimeSpec]

|*TIMESTAMP*
|{instancio-core-doc}/org/instancio/generator/specs/LocalDateTimeSpec.html[LocalDateTimeSpec]

|*TIME_WITH_TIMEZONE*
|{instancio-core-doc}/org/instancio/generator/specs/OffsetTimeSpec.html[OffsetTimeSpec]

|*TIMESTAMP_WITH_TIMEZONE*
|{instancio-core-doc}/org/instancio/generator/specs/ZonedDateTimeSpec.html[ZonedDateTimeSpec]
|===

=== For binary data

By default, all of binary type are generated by {instancio-core-doc}/org/instancio/generator/specs/ByteSpec.html[ByteSpec].

For `BINARY`, `VARBINARY`::
+
[cols="2,2"]
|===
|`ColumnMeta.size()`
|ValueGenerator

| `<= 16`(less than or equal to 16). _UUID is 16 bytes_.
| Same as `ColumnMeta.size()`

| `> 16 && <= 64`(between 16 and 64)
| Length is between 16 and `ColumnMeta.size()`

| `> 64`(more than 64)
| Length is between 64 and `Math.min(ColumnMeta.size(), 256)`
|===

For `LONGVARBINARY`, `BLOB`::
+
* Generate binary with length between `_1024_` and `_2048_`.

== Special types

By type name::

* `UUID` - {instancio-core-doc}/org/instancio/generator/specs/UUIDSpec.html[UUIDSpec]

== Not supported JDBCTypes

* `ARRAY`, `STRUCT`
** TODO: Oracle, PostgreSQL support array/struct types.
* `ROWID`, `NULL`, `JAVA_OBJECT`, `DISTINCT`, `OTHER`
* `SQLXML` - Won't generate values
** TODO: Oracle, PostgreSQL, SQL Server support array/struct types.
* `REF`, `REF_CURSOR`, `DATALINK`
