var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":188,"id":2930,"methods":[{"el":63,"sc":2,"sl":63}],"name":"FoxgloveTestListenerTest","sl":41},{"el":58,"id":2930,"methods":[{"el":51,"sc":3,"sl":44},{"el":57,"sc":3,"sl":53}],"name":"FoxgloveTestListenerTest.CleanupListener","sl":42},{"el":101,"id":2935,"methods":[{"el":72,"sc":3,"sl":71},{"el":75,"sc":3,"sl":74},{"el":84,"sc":3,"sl":77},{"el":100,"sc":3,"sl":89}],"name":"FoxgloveTestListenerTest.TransactionalTest","sl":70},{"el":187,"id":2942,"methods":[{"el":152,"sc":3,"sl":138},{"el":168,"sc":3,"sl":157},{"el":174,"sc":3,"sl":170},{"el":186,"sc":3,"sl":179}],"name":"FoxgloveTestListenerTest.BasicTest","sl":114},{"el":133,"id":2942,"methods":[{"el":122,"sc":4,"sl":117},{"el":132,"sc":4,"sl":124}],"name":"FoxgloveTestListenerTest.BasicTest.SampleConfig","sl":116}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_126":{"methods":[{"sl":138}],"name":"byJavaReflection","pass":true,"statements":[{"sl":145},{"sl":150}]},"test_206":{"methods":[{"sl":89}],"name":"transactional","pass":true,"statements":[{"sl":93},{"sl":98}]},"test_6":{"methods":[{"sl":157}],"name":"bySpringBeans","pass":true,"statements":[{"sl":161},{"sl":166}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [206], [], [], [], [206], [], [], [], [], [206], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [126], [], [], [], [], [], [], [126], [], [], [], [], [126], [], [], [], [], [], [], [6], [], [], [], [6], [], [], [], [], [6], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
