package guru.mikelue.foxglove.instancio;

import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;

import guru.mikelue.misc.testlib.AbstractTestBase;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

public class ByteArraySpecTest extends AbstractTestBase {
	private final static int REPEAT_COUNT = 8;

	public ByteArraySpecTest() {}

	@BeforeEach
	void setup() {}

	@AfterEach
	void tearDown() {}

	/**
	 * Tests the fixed length for generated byte array.
	 */
	@RepeatedTest(REPEAT_COUNT)
	void fixedLength()
	{
		final int arrayLength = gen().ints().range(16, 32).get();

		var testedSpec = new ByteArraySpec()
			.length(arrayLength);

		byte[] testedResult = testedSpec.get();

		assertThat(testedResult)
			.isNotNull()
			.hasSize(arrayLength)
			.doesNotContain((byte)0x00);
	}

	/**
	 * Tests the random length.
	 */
	@RepeatedTest(REPEAT_COUNT)
	void randomLength()
	{
		final int minLength = 16;
		final int maxLength = 32;

		var testedSpec = new ByteArraySpec()
			.minLength(minLength).maxLength(maxLength);

		byte[] testedResult = testedSpec.get();

		assertThat(testedResult)
			.isNotNull()
			.hasSizeBetween(minLength, maxLength)
			.doesNotContain((byte)0x00);
	}

	/**
	 * Tests the null array.
	 */
	@Test
	void nullable()
	{
		var testedSpec = new ByteArraySpec()
			.nullable();

		await()
			.atMost(5, TimeUnit.SECONDS)
			.untilAsserted(() -> {
				assertThat(testedSpec.get()).isNull();
			});
	}

	/**
	 * Tests the zero element in generated array.
	 */
	@Test
	void zeroElements()
	{
		var testedSpec = new ByteArraySpec()
			.length(512)
			.zeroElements();

		await()
			.atMost(5, TimeUnit.SECONDS)
			.untilAsserted(() -> {
				assertThat(testedSpec.get())
					.isNotNull()
					.contains((byte)0x00);
			});
	}
}
