var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":265,"id":1969,"methods":[{"el":23,"sc":2,"sl":23},{"el":55,"sc":2,"sl":39},{"el":65,"sc":2,"sl":58},{"el":74,"sc":2,"sl":67},{"el":92,"sc":2,"sl":76},{"el":116,"sc":2,"sl":106},{"el":132,"sc":2,"sl":119},{"el":148,"sc":2,"sl":133},{"el":164,"sc":2,"sl":151},{"el":180,"sc":2,"sl":165},{"el":196,"sc":2,"sl":183},{"el":212,"sc":2,"sl":197},{"el":254,"sc":2,"sl":244},{"el":257,"sc":2,"sl":256},{"el":264,"sc":2,"sl":259}],"name":"JUnit5SimpleTest","sl":20},{"el":104,"id":1980,"methods":[{"el":103,"sc":3,"sl":96}],"name":"JUnit5SimpleTest.CarsInSilver","sl":95},{"el":232,"id":1999,"methods":[{"el":231,"sc":3,"sl":222}],"name":"JUnit5SimpleTest.NestedTest","sl":221}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_127":{"methods":[{"sl":106}],"name":"byProviderClass","pass":true,"statements":[{"sl":111}]},"test_131":{"methods":[{"sl":165}],"name":"byListOfTableFacet","pass":true,"statements":[{"sl":170},{"sl":175}]},"test_136":{"methods":[{"sl":222}],"name":"nestedByFields","pass":true,"statements":[{"sl":226}]},"test_155":{"methods":[{"sl":39}],"name":"byFields","pass":true,"statements":[{"sl":44},{"sl":50}]},"test_261":{"methods":[{"sl":133}],"name":"byArrayOfTableFacet","pass":true,"statements":[{"sl":138},{"sl":143}]},"test_291":{"methods":[{"sl":76}],"name":"byMethods","pass":true,"statements":[{"sl":81},{"sl":87}]},"test_294":{"methods":[{"sl":244}],"name":"byTableFacetWithName","pass":true,"statements":[{"sl":249}]},"test_298":{"methods":[{"sl":197}],"name":"byStreamOfTableFacet","pass":true,"statements":[{"sl":202},{"sl":207}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [155], [], [], [], [], [155], [], [], [], [], [], [155], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [291], [], [], [], [], [291], [], [], [], [], [], [291], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [127], [], [], [], [], [127], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [261], [], [], [], [], [261], [], [], [], [], [261], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [131], [], [], [], [], [131], [], [], [], [], [131], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [298], [], [], [], [], [298], [], [], [], [], [298], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [136], [], [], [], [136], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [294], [], [], [], [], [294], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
