var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":95,"id":2909,"methods":[{"el":23,"sc":2,"sl":23},{"el":26,"sc":2,"sl":25},{"el":29,"sc":2,"sl":28},{"el":52,"sc":2,"sl":35},{"el":94,"sc":2,"sl":53}],"name":"GeneratingUtilsTest","sl":22}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_2":{"methods":[{"sl":35}],"name":"[4] [NULLABLE], [NULLABLE], true","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_201":{"methods":[{"sl":35}],"name":"[9] [DEFAULT_VALUE], [NULLABLE], false","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_234":{"methods":[{"sl":35}],"name":"[5] [DEFAULT_VALUE], [DEFAULT_VALUE], true","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_270":{"methods":[{"sl":35}],"name":"[7] [NULLABLE, AUTO_INCREMENT], [NULLABLE], false","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_39":{"methods":[{"sl":35}],"name":"[2] [GENERATED], [GENERATED], true","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_62":{"methods":[{"sl":35}],"name":"[6] [AUTO_INCREMENT, GENERATED], [AUTO_INCREMENT], false","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_68":{"methods":[{"sl":35}],"name":"[1] [], [], true","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_82":{"methods":[{"sl":35}],"name":"[8] [NULLABLE, DEFAULT_VALUE], [DEFAULT_VALUE], false","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]},"test_94":{"methods":[{"sl":35}],"name":"[3] [AUTO_INCREMENT], [AUTO_INCREMENT], true","pass":true,"statements":[{"sl":42},{"sl":46},{"sl":50}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [94, 270, 39, 201, 234, 62, 82, 68, 2], [], [], [], [], [], [], [94, 270, 39, 201, 234, 62, 82, 68, 2], [], [], [], [94, 270, 39, 201, 234, 62, 82, 68, 2], [], [], [], [94, 270, 39, 201, 234, 62, 82, 68, 2], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
