+++
title = 'Introduction'
description = 'Welcome to the Foxglove. A library for generating data for RDB.'
+++

## Motivation

When we are preparing data of RDB for tests, the tedious and tricky part is to write correct https://en.wikipedia.org/wiki/Data_manipulation_language[DML] for data insertion.
{foxglove-link} is a library that helps you to generating data by auto schema-inspection and table facet(rules to generate data).

While preparing data for unit tests over databases, the key things are:

. Preparing values for columns in `WHERE` clause of SQL or clause may *FILTERING* data(e.g. `INNER JOIN`).
. Some critical values to be asserted or counting number of results affected by exercised SQL.
. While tearing down the tests, you may like to delete only the data you have inserted.
	* Specify some fixed values to irrelevant columns could help

That is, how {foxglove-link} helps you:

. Just provide values for specified columns.
. Give the critical values you need to check.
. Don't have to care about irrelevant, _non-nullable(and no default value)_ columns.

Other data that is irrelevant to your tests will be _generated automatically_ by {foxglove-link}.

---

.Preparing data
[source,java]
----
include::{example-dir}/TableFacetTest.java[tag=basicUsage,indent=0]
----

The data could be used for:

. There could be `0 ~ 1` matched row for any query of the SQL
+
[source,sql]
----
SELECT *
FROM ap_car
WHERE cr_brand = ?
	AND cr_model = ?
----

. Since `cr_created_at` will be generated randomly by default,
	you can check the values of the column for the correctness of ordering.
+
[source,sql]
----
SELECT *
FROM ap_car
WHERE cr_brand = ?
ORDER BY cr_created_at DESC
----

## Integration

* See link:/quickstart/junit[JUnit 5 Quick Start] for usage with {junit5-link}.
* See link:/quickstart/springframework[SpringFramework Quick Start] for usage with https://docs.spring.io/spring-framework/reference/6.0/testing/support-jdbc.html[SprinFramwork - JDBC Testing Support].

## Requirements

* https://openjdk.org/projects/jdk/17/[Java 17+]

## Documentations

* link:/quickstart/[Quick starts], link:/docs/[Docs]
* link:/maven-site[Maven Site], link:/maven-site/apidocs[Javadocs(Maven Site)]

## Installation

include::content/snippets/installation.adoc[]

## Credits

Thanks to {instancio-link} project for its excellent data generation capabilities.
