-- 1. Oracle (12c+)
CREATE SEQUENCE ap_types_seq START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE ap_types (
    tp_id        NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tp_name      VARCHAR2(32)  NOT NULL UNIQUE,
    tp_size      NUMBER(10)    DEFAULT 0 NOT NULL,
    tp_key       RAW(64)       NULL,
    tp_color     VARCHAR2(32)  NULL,
    tp_time_created   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tp_time_updated   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER ap_types_upd_trg
BEFORE UPDATE ON ap_types
FOR EACH ROW
BEGIN
    :NEW.tp_time_updated := CURRENT_TIMESTAMP;
END;
/

-- 2. Microsoft SQL Server
CREATE TABLE ap_types (
    tp_id        BIGINT        IDENTITY(1,1) PRIMARY KEY,
    tp_name      VARCHAR(32)   NOT NULL UNIQUE,
    tp_size      INT           DEFAULT 0 NOT NULL,
    tp_key       VARBINARY(64) NULL,
    tp_color     VARCHAR(32)   NULL,
    tp_time_created   DATETIME2     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tp_time_updated   DATETIME2     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER trg_ap_types_upd
ON ap_types
AFTER UPDATE
AS
BEGIN
    UPDATE ap_types
    SET tp_time_updated = CURRENT_TIMESTAMP
    FROM inserted i
    WHERE ap_types.tp_id = i.tp_id;
END;
GO

-- 3. MySQL 8.0+
CREATE TABLE ap_types (
    tp_id        BIGINT        AUTO_INCREMENT PRIMARY KEY,
    tp_name      VARCHAR(32)   NOT NULL UNIQUE,
    tp_size      INT           DEFAULT 0 NOT NULL,
    tp_key       VARBINARY(64) NULL,
    tp_color     VARCHAR(32)   NULL,
    tp_time_created   DATETIME     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tp_time_updated   DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB;

-- 4. PostgreSQL
CREATE TABLE ap_types (
    tp_id        BIGSERIAL     PRIMARY KEY,
    tp_name      VARCHAR(32)   NOT NULL UNIQUE,
    tp_size      INT           DEFAULT 0 NOT NULL,
    tp_key       BYTEA         NULL,
    tp_color     VARCHAR(32)   NULL,
    tp_time_created   TIMESTAMPTZ   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tp_time_updated   TIMESTAMPTZ   DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION update_tp_time_updated()
RETURNS TRIGGER AS $$
BEGIN
    NEW.tp_time_updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ap_types_upd
BEFORE UPDATE ON ap_types
FOR EACH ROW
EXECUTE FUNCTION update_tp_time_updated();

-- 5. Apache Derby
CREATE TABLE ap_types (
    tp_id        BIGINT        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tp_name      VARCHAR(32)   NOT NULL UNIQUE,
    tp_size      INT           DEFAULT 0 NOT NULL,
    tp_key       VARCHAR(64) FOR BIT DATA NULL,
    tp_color     VARCHAR(32)   NULL,
    tp_time_created   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tp_time_updated   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER trg_ap_types_upd
AFTER UPDATE ON ap_types
REFERENCING NEW AS n OLD AS o
FOR EACH ROW
UPDATE ap_types SET tp_time_updated = CURRENT_TIMESTAMP
WHERE tp_id = n.tp_id;

-- 6. HSQLDB (HyperSQL)
CREATE TABLE ap_types (
    tp_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tp_name      VARCHAR(32)   NOT NULL UNIQUE,
    tp_size      INTEGER       DEFAULT 0 NOT NULL,
    tp_key       VARBINARY(64) NULL,
    tp_color     VARCHAR(32)   NULL,
    tp_time_created   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tp_time_updated   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER trg_ap_types_upd
BEFORE UPDATE ON ap_types
REFERENCING NEW ROW AS n
FOR EACH ROW
SET n.tp_time_updated = CURRENT_TIMESTAMP;
