CREATE TABLE ap_types (
    tp_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tp_name      VARCHAR(32)   UNIQUE NOT NULL,
    tp_size      INTEGER       DEFAULT 0 NOT NULL,
    tp_key       VARBINARY(64) NULL,
    tp_color     VARCHAR(32)   NULL,
	tp_int_array INTEGER ARRAY[8] NULL,
	tp_boolean BOOLEAN NULL,
	tp_size_computed INTEGER GENERATED ALWAYS AS (tp_size - 1),
    tp_time_created   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tp_time_updated   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);
