CREATE TABLE ap_types (
	tp_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tp_name VARCHAR2(32) NOT NULL,
	tp_size NUMBER(10) DEFAULT 0 NOT NULL,
	tp_key RAW(256),
	tp_color VARCHAR2(32),
	tp_computed_size NUMBER(10) GENERATED ALWAYS AS (tp_size - 1),
	tp_time_created TIMESTAMP NOT NULL,
	tp_time_updated TIMESTAMP NOT NULL
);
