var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":279,"id":2770,"methods":[{"el":28,"sc":2,"sl":28},{"el":37,"sc":2,"sl":30},{"el":40,"sc":2,"sl":39},{"el":46,"sc":2,"sl":42},{"el":270,"sc":2,"sl":266},{"el":278,"sc":2,"sl":272}],"name":"FoxgloveJUnitExtensionTest","sl":24},{"el":81,"id":2776,"methods":[{"el":61,"sc":3,"sl":56},{"el":68,"sc":3,"sl":63},{"el":74,"sc":3,"sl":70},{"el":80,"sc":3,"sl":76}],"name":"FoxgloveJUnitExtensionTest.OnClassLevel","sl":55},{"el":116,"id":2784,"methods":[{"el":97,"sc":3,"sl":91},{"el":103,"sc":3,"sl":102},{"el":109,"sc":3,"sl":105},{"el":115,"sc":3,"sl":111}],"name":"FoxgloveJUnitExtensionTest.OnDefaultSources","sl":87},{"el":188,"id":2791,"methods":[{"el":176,"sc":3,"sl":167},{"el":187,"sc":3,"sl":178}],"name":"FoxgloveJUnitExtensionTest.OnTypedProviders","sl":122},{"el":129,"id":2791,"methods":[{"el":128,"sc":4,"sl":124}],"name":"FoxgloveJUnitExtensionTest.OnTypedProviders.InnerDataGeneratorProvider","sl":123},{"el":137,"id":2793,"methods":[{"el":136,"sc":4,"sl":132}],"name":"FoxgloveJUnitExtensionTest.OnTypedProviders.InnerTableFacetProvider","sl":131},{"el":157,"id":2795,"methods":[{"el":150,"sc":4,"sl":142},{"el":156,"sc":4,"sl":152}],"name":"FoxgloveJUnitExtensionTest.OnTypedProviders.StaticInnerDataGeneratorProvider","sl":139},{"el":165,"id":2803,"methods":[{"el":164,"sc":4,"sl":160}],"name":"FoxgloveJUnitExtensionTest.OnTypedProviders.StaticInnerTableFacetProvider","sl":159},{"el":217,"id":2809,"methods":[{"el":204,"sc":3,"sl":195},{"el":210,"sc":3,"sl":206},{"el":216,"sc":3,"sl":212}],"name":"FoxgloveJUnitExtensionTest.OnNamedProviders","sl":194},{"el":264,"id":2815,"methods":[{"el":254,"sc":3,"sl":250},{"el":263,"sc":3,"sl":256}],"name":"FoxgloveJUnitExtensionTest.OuterConfig","sl":223},{"el":240,"id":2815,"methods":[{"el":239,"sc":4,"sl":229}],"name":"FoxgloveJUnitExtensionTest.OuterConfig.InnerTest","sl":225},{"el":248,"id":2817,"methods":[{"el":247,"sc":4,"sl":243}],"name":"FoxgloveJUnitExtensionTest.OuterConfig.OuterTableFacetProvider","sl":242}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_108":{"methods":[{"sl":102}],"name":"nothing","pass":true,"statements":[]},"test_114":{"methods":[{"sl":229}],"name":"useOuterConfig","pass":true,"statements":[{"sl":237}]},"test_15":{"methods":[{"sl":91}],"name":"defaultSources","pass":true,"statements":[{"sl":95}]},"test_184":{"methods":[{"sl":56}],"name":"onClassLevel_1","pass":true,"statements":[{"sl":59}]},"test_285":{"methods":[{"sl":167}],"name":"providersOfNonStaticMember","pass":true,"statements":[{"sl":174}]},"test_291":{"methods":[{"sl":63}],"name":"onClassLevel_2","pass":true,"statements":[{"sl":66}]},"test_84":{"methods":[{"sl":178}],"name":"providersOfStaticMember","pass":true,"statements":[{"sl":185}]},"test_96":{"methods":[{"sl":195}],"name":"namedProviders","pass":true,"statements":[{"sl":202}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [184], [], [], [184], [], [], [], [291], [], [], [291], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [15], [], [], [], [15], [], [], [], [], [], [], [108], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [285], [], [], [], [], [], [], [285], [], [], [], [84], [], [], [], [], [], [], [84], [], [], [], [], [], [], [], [], [], [96], [], [], [], [], [], [], [96], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [114], [], [], [], [], [], [], [], [114], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
